-- MySQL Script generated by MySQL Workbench
-- Tue Aug 20 15:26:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projects
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projects` ;

-- -----------------------------------------------------
-- Schema projects
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projects` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `projects` ;

-- -----------------------------------------------------
-- Table `projects`.`project_manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projects`.`project_manager` ;

CREATE TABLE IF NOT EXISTS `projects`.`project_manager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projects`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projects`.`project` ;

CREATE TABLE IF NOT EXISTS `projects`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `project_manager_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_project_manager_idx` (`project_manager_id` ASC),
  CONSTRAINT `fk_project_project_manager`
    FOREIGN KEY (`project_manager_id`)
    REFERENCES `projects`.`project_manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
